# Generated by Django 5.2.4 on 2026-06-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckowner',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truckowner',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('loading_location', models.CharField(max_length=255)),
                ('unloading_location', models.CharField(max_length=255)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.truckowner')),
            ],
        ),
    ]
