# Generated by Django 5.2.4 on 2026-06-26 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_truckowner_available_truckowner_rate_per_km_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2026, 6, 26)),
            preserve_default=False,
        ),
    ]
